//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilAndGasProcessor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OilAndGasProcessor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 328.042.
        /// </summary>
        internal static string BaseHorizonDefaultValue {
            get {
                return ResourceManager.GetString("BaseHorizonDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating ....
        /// </summary>
        internal static string CalculatingText {
            get {
                return ResourceManager.GetString("CalculatingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../../Default_Depth_Values.txt.
        /// </summary>
        internal static string DefaultDepthValuesFilePath {
            get {
                return ResourceManager.GetString("DefaultDepthValuesFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth values not of the same number in each line.
        /// </summary>
        internal static string DepthValuesNotOfTheSameNumberErrorText {
            get {
                return ResourceManager.GetString("DepthValuesNotOfTheSameNumberErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9842.52.
        /// </summary>
        internal static string FluidContactDefaultValue {
            get {
                return ResourceManager.GetString("FluidContactDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      This application calculates the volume of oil and gas above the fluid contact
        ///      It uses approximation by deviding the top horizon&apos;s cell&apos;s lateral into smaller laterals
        ///      The precision is the number of time you divide by the lateral.
        ///     The higher you raize the precision, the more accurate the results, but the more time the calculator takes to
        ///     calculate the results.
        ///    .
        /// </summary>
        internal static string InformationMessage {
            get {
                return ResourceManager.GetString("InformationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Error.
        /// </summary>
        internal static string InputErrorText {
            get {
                return ResourceManager.GetString("InputErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        internal static string LateralDefaultValue {
            get {
                return ResourceManager.GetString("LateralDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of lines 2.
        /// </summary>
        internal static string MinimumNumberOfLines2 {
            get {
                return ResourceManager.GetString("MinimumNumberOfLines2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a parsable double.
        /// </summary>
        internal static string NotParsableDouble {
            get {
                return ResourceManager.GetString("NotParsableDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not a parsable int.
        /// </summary>
        internal static string NotParsableInt {
            get {
                return ResourceManager.GetString("NotParsableInt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not Under 0.
        /// </summary>
        internal static string NotUnderZero {
            get {
                return ResourceManager.GetString("NotUnderZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the lines have non parsable to int strings or negative numbers.
        /// </summary>
        internal static string SomeLinesHaveNonParsableToIntStringOrNegativeNumbers {
            get {
                return ResourceManager.GetString("SomeLinesHaveNonParsableToIntStringOrNegativeNumbers", resourceCulture);
            }
        }
    }
}
